roles: # the order is relevant here!
  - ROLE_GHOST
  - ROLE_USER
  - ROLE_ADMIN
  - ROLE_OP
default_role: ROLE_USER
languages:
  de_de: Deutsch
  en_us: English (US)
default_language: en_us
themes:
  amelia:    Amelia
  cerulean:  Cerulean
  cosmo:     Cosmo
  cyborg:    Cyborg
  darkly:    Darkly
  flatly:    Flatly
  journal:   Journal
  lumen:     Lumen
  readable:  Readable
  simplex:   Simplex
  slate:     Slate
  spacelab:  Spacelab
  superhero: Superhero
  united:    United
  yeti:      Yeti
