# Never edit this file directly!
# Instead, copy it and name the copy 'parameters.yml'. Edit the copy only.

# Your database connection. Set the user, password and dbname. If needed, change
# the host.
database:
  driver:   pdo_mysql
  host:     127.0.0.1
  user:     yourusername
  password: yourpassword
  dbname:   yourdatabasename
  charset:  utf8
  driverOptions:
    1002: SET NAMES utf8

# Your secret.
# This is a random string of characters. Set it to anything you want, but make it
# at least 10 characters long and random. You cannot leave this field blank.
# Something like this is good: http://www.random.org/strings/?num=1&len=20&digits=on&upperalpha=on&loweralpha=on&format=plain
secret: ''

# Set this to false to enable production mode. This will:
#   - turn off Twig auto-reloads
#   - turn off on-demand generation of Doctrine proxies
#   - create links to versioned assets
# See the README.md for more details.
debug: true

# Directory where generated Doctrine proxies are stored. You can use either
# relative paths or absolute ones (on *nix systems).
doctrine_proxies: tmp/doctrine-proxies/

# If you change something in here, you have to adjust the schema.orm.yml and your
# database as well. Generally, there is no reason to touch this.
session:
  db_table:    sessions
  db_id_col:   id
  db_data_col: data
  db_time_col: mtime
